增加部分文档
ivanallen/thor pull request #21
Opened 2020-04-04 07:15 UTC by fisheuler

2020-04-04 11:24 UTC, ivanallen requested changes
文件名使用英文。中文对 shell 命令不友好。

2020-04-04 11:31 UTC, ivanallen commented on README.md
> +[VS Subtitles Editor ](https://marketplace.visualstudio.com/items?itemName=pepri.subtitles-editor)
[VS Subtitles Editor]，多了个空格。

2020-04-05 01:51 UTC, fisheuler commented on README.md
> +[VS Subtitles Editor ](https://marketplace.visualstudio.com/items?itemName=pepri.subtitles-editor)
已调整

2020-04-05 01:54 UTC, ivanallen approved these changes

2020-04-05 01:54 UTC, merged

2020-04-05 01:56 UTC, ivanallen commented
@all-contibutors please add @fisheuler for doc

2020-04-05 01:58 UTC, ivanallen commented
@all-contributors please add @fisheuler for doc